{{- if and (not .Values.influxdb.existingSecret) .Values.influxdb.adminToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "influxdb3-core.secretName" . }}
  labels:
    {{- include "influxdb3-core.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.influxdb.existingSecretKey }}: {{ .Values.influxdb.adminToken | quote }}
{{- end }}
